import type { GadgetSettings } from "gadget-server";

export const settings: GadgetSettings = {
  type: "gadget/settings/v1",
  frameworkVersion: "v1.1.0",
  plugins: {
    connections: {
      shopify: {
        apiVersion: "2025-07",
        enabledModels: [
          "shopifyBillingAddress",
          "shopifyCart",
          "shopifyCartLineItem",
          "shopifyCheckout",
          "shopifyCheckoutAppliedGiftCard",
          "shopifyCheckoutLineItem",
          "shopifyCheckoutShippingRate",
          "shopifyCollection",
          "shopifyCompany",
          "shopifyCompanyAddress",
          "shopifyCompanyContact",
          "shopifyCompanyContactRole",
          "shopifyCompanyContactRoleAssignment",
          "shopifyCompanyLocation",
          "shopifyCustomer",
          "shopifyCustomerAddress",
          "shopifyCustomerMergeable",
          "shopifyDiscount",
          "shopifyDiscountCode",
          "shopifyDiscountCustomerBuysCollection",
          "shopifyDiscountCustomerBuysProduct",
          "shopifyDiscountCustomerBuysProductVariant",
          "shopifyDiscountCustomerGetsCollection",
          "shopifyDiscountCustomerGetsProduct",
          "shopifyDiscountCustomerGetsProductVariant",
          "shopifyDiscountRedeemCode",
          "shopifyDuty",
          "shopifyFulfillment",
          "shopifyFulfillmentEvent",
          "shopifyFulfillmentLineItem",
          "shopifyGiftCard",
          "shopifyOrder",
          "shopifyOrderAdjustment",
          "shopifyOrderLineItem",
          "shopifyOrderRisk",
          "shopifyOrderTransaction",
          "shopifyPriceRule",
          "shopifyProduct",
          "shopifyProductVariant",
          "shopifyRefund",
          "shopifyRefundDuty",
          "shopifyRefundLineItem",
          "shopifyShippingAddress",
          "shopifyShippingLine",
          "shopifyTenderTransaction",
        ],
        type: "partner",
        scopes: [
          "read_customers",
          "write_customers",
          "read_customer_merge",
          "read_customer_events",
          "read_orders",
          "write_orders",
          "read_fulfillments",
          "read_discounts",
          "write_discounts",
          "read_products",
          "read_price_rules",
          "read_discounts_allocator_functions",
          "write_discounts_allocator_functions",
          "read_cart_transforms",
          "write_cart_transforms",
          "read_gift_cards",
          "write_gift_cards",
        ],
        customerAuthenticationEnabled: true,
      },
    },
  },
};
