import type { GadgetModel } from "gadget-server";

// This file describes the schema for the "shopifyShop" model, go to https://brewdog.gadget.app/edit to view/edit your model in Gadget
// For more information on how to update this file http://docs.gadget.dev

export const schema: GadgetModel = {
  type: "gadget/model-schema/v1",
  storageKey: "DataModel-Shopify-Shop",
  fields: {
    doubleDiscount: {
      type: "boolean",
      shopifyMetafield: {
        privateMetafield: false,
        namespace: "brewdog",
        key: "efp_double_discount",
        metafieldType: "boolean",
        allowMultipleEntries: false,
      },
      storageKey: "MnbMRd52fwzK",
    },
  },
  shopify: {
    fields: [
      "address1",
      "address2",
      "billingAddresses",
      "cartLineItems",
      "carts",
      "checkoutApiSupported",
      "checkoutAppliedGiftCards",
      "checkoutLineItems",
      "checkoutShippingRates",
      "checkouts",
      "city",
      "collections",
      "company",
      "companyAddress",
      "companyContact",
      "companyContactRole",
      "companyContactRoleAssignment",
      "companyLocation",
      "cookieConsentLevel",
      "country",
      "countryCode",
      "countryName",
      "countyTaxes",
      "currency",
      "customerAccountsV2",
      "customerAddresses",
      "customerEmail",
      "customerMergeables",
      "customers",
      "discountCodes",
      "discountCustomerBuysCollections",
      "discountCustomerBuysProductVariants",
      "discountCustomerBuysProducts",
      "discountCustomerGetsCollections",
      "discountCustomerGetsProductVariants",
      "discountCustomerGetsProducts",
      "discountRedeemCodes",
      "discounts",
      "domain",
      "duties",
      "eligibleForCardReaderGiveaway",
      "eligibleForPayments",
      "email",
      "enabledPresentmentCurrencies",
      "finances",
      "forceSsl",
      "fulfillmentEvents",
      "fulfillmentLineItems",
      "fulfillments",
      "gdprRequests",
      "giftCards",
      "googleAppsDomain",
      "googleAppsLoginEnabled",
      "hasDiscounts",
      "hasGiftCards",
      "hasStorefront",
      "ianaTimezone",
      "latitude",
      "longitude",
      "marketingSmsContentEnabledAtCheckout",
      "moneyFormat",
      "moneyInEmailsFormat",
      "moneyWithCurrencyFormat",
      "moneyWithCurrencyInEmailsFormat",
      "multiLocationEnabled",
      "myshopifyDomain",
      "name",
      "orderAdjustments",
      "orderLineItems",
      "orderRisks",
      "orderTransactions",
      "orders",
      "passwordEnabled",
      "phone",
      "planDisplayName",
      "planName",
      "preLaunchEnabled",
      "priceRules",
      "primaryLocale",
      "productVariants",
      "products",
      "province",
      "provinceCode",
      "refundDuties",
      "refundLineItems",
      "refunds",
      "requiresExtraPaymentsAgreement",
      "setupRequired",
      "shippingAddresses",
      "shippingLines",
      "shopOwner",
      "shopifyCreatedAt",
      "shopifyUpdatedAt",
      "source",
      "syncs",
      "taxShipping",
      "taxesIncluded",
      "tenderTransactions",
      "timezone",
      "transactionalSmsDisabled",
      "weightUnit",
      "zipCode",
    ],
  },
};
